FROM node:14-alpine

WORKDIR /app
COPY package.json ./
RUN npm install

COPY . .

RUN npm run build
#RUN rm -f .env.production
#RUN rm -f .env.development

#COPY .env.development ./

CMD ["npx", "next", "start"]
